name: DiskyApi CI/CD Azure App Service

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Build with Gradle
        run: ./gradlew war
        working-directory: .
      - name: Deploying to Azure App Service
        uses: Azure/webapps-deploy@v2
        with:
          app-name: prod-diskyapi-as
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: build/libs/ROOT.war